### ISSUE TITLE
Can't update password

### ISSUE THREAD

**Issue by gduverger** [encrypted-dev/userbase#123]
I keep getting a “Incorrect password” error message when I try to update my password in the admin page. I even tried to replicate the format used in the temporary password.

<img width="732" alt="Screen Shot 2020-03-05 at 12 30 10 PM" src="https://user-images.githubusercontent.com/93743/76008264-57ad9b00-5edd-11ea-80f5-6b0a174c9820.png">

<img width="257" alt="Screen Shot 2020-03-05 at 12 32 28 PM" src="https://user-images.githubusercontent.com/93743/76008289-65fbb700-5edd-11ea-8ce0-eafd76074855.png">

**Comment by j-berman** [comment]
Including the most recent temporary password emailed to you as your "Current Password" should work. Not exactly sure what could be causing this since I'm not able to reproduce it, but here are a couple plausible things that could be happening:

1. Is it possible the password generator is overwriting the Current Password field with the newly generated one? If this is happening, maybe just try copy pasting a new password, as opposed to letting the generator fill the field for you. I think we should offer the ability to show your password to make sure this isn't happening.

2. Is it possible that you clicked "Forgot Password" more than once and are not using the most recent temporary password emailed to you?

If not either of these 2, will think some more on what could be causing this :)
