### ISSUE TITLE
Uncaught SyntaxError on openDatabase

### ISSUE THREAD

**Issue by gduverger** [encrypted-dev/userbase#124]
I get an `Uncaught SyntaxError: Unexpected token ','` error when I do…
```
userbase.openDatabase({'…', function(items) {…}})
```

But not when I replace it with…
```
userbase.openDatabase({databaseName: '…', changeHandler: function(items) {…}})
```

(I'm using `https://sdk.userbase.com/1/userbase.js`.)

**Comment by j-berman** [comment]
I believe this is an expected javascript error, no?

Try creating an object in a js console like this:

`const obj = { '...', function() {} }`

You'll get the same syntax error.

You _need_ to include the keys `databaseName` and `changeHandler`. Object values must have associated keys in javascript. Otherwise the Userbase SDK wouldn't know which value is the databaseName and which value is the changeHandler in your code throwing the syntax error.

**Comment by gduverger** [comment]
Right. For some reasons, it didn't raise an error for `userbase.signIn({username, password, rememberMe: 'session'})`. Regardless, if that's the case, it might be good to update the documentation to be more explicit (https://userbase.com/docs/sdk/open-database/).

**Comment by j-berman** [comment]
Documentation updated! Thanks again Georges!
