### ISSUE TITLE
Signing In After Deleting Via SDK Results In `UsernameOrPasswordMismatch`

### ISSUE THREAD

**Issue by rhucle** [encrypted-dev/userbase#134]
Odd error. But signing the user in and unmarking his account as pending deletion might be a better behavior.

**Comment by j-berman** [comment]
Thanks for your feedback!

signIn() now throws the error UserPendingDeletion if the user signs in with the correct password after deleting their account, but the user's account has not been purged from the server yet.

We're planning on adding support for account recovery in the future as a separate feature, rather than make recovery the default behavior for all apps. After a user deletes their account, don't think the user should need to be concerned that someone could still get access to their account with their password. We're planning to enable recovery manually from the admin side (so a user would need to reach out to you, and then you can recover their account), as well as potentially adding recovery by email.

How's that sound?

**Comment by rhucle** [comment]
Nice. That should work.
