### ISSUE TITLE
WebSocket error on signIn in Firefox

### ISSUE THREAD

**Issue by netzwerg** [encrypted-dev/userbase#163]
In Firefox, invoking the `signIn` method leads to a WebSocket error:

<img width="844" alt="Screenshot 2020-06-28 at 13 30 59" src="https://user-images.githubusercontent.com/439387/85946356-28b3ad00-b944-11ea-9a1d-1a7f897e289c.png">

The same code works in Chrome and Safari.

This happens with a create-react-app project, on http://localhost:3000

Versions used:
userbase-js 2.0.0
Firefox Developer Edition 78.0b9
Firefox 77.0.1

**Comment by j-berman** [comment]
Ack'd, working on this and will provide a detailed write-up on it. Thank you for reporting.

**Comment by rahel-luethy-fhnw** [comment]
Can confirm that the bug is fixed in 2.0.1 – thank you so much!

**Comment by netzwerg** [comment]
Can confirm that the bug is fixed in 2.0.1 – thank you so much!

**Comment by j-berman** [comment]
### Summary of the bug

The AES-KW crypto algorithm was introduced in #155 (userbase-js v2.0.0). Clients used AES-KW to wrap private keys, which were then stored on the Userbase server. The client then used AES-KW again to unwrap the private keys in order to sign in.

The AES-KW unwrap function is [broken in Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1563236), so userbase-js v2.0.0 functions signUp(), signIn(), and init() are broken in Firefox.

### Solution

We replaced usage of the AES-KW algorithm entirely with AES-GCM in userbase-js v2.0.1 (#164).

userbase-js versions <= 2.0.0 still work. When a developer updates to version 2.0.1, the userbase-js client generates new private keys, which are then encrypted and stored on the server in place of the wrapped private keys and are used to authenticate the user in subsequent visits to the app.

### Preventing cross-browser bugs in the future

We’ve added Firefox to our test suite in #165. Every PR will now run our entire set of unit tests against Firefox.

We have a series of manual tests to run against Safari, Safari iOS, and Chrome Android as well. For the immediate future, running these manual tests is a matter of discipline on our end that we will stick to.

We're also exploring incorporating BrowserStack into our CI pipeline to automate testing across a wider range of browsers, but it’s not on the immediate roadmap.
