### ISSUE TITLE
Question: Feasible to use API Gateway Web Sockets + Lambda Instead of EC2?

### ISSUE THREAD

**Issue by pfeilbr** [encrypted-dev/userbase#166]
Thank you for making this OSS.  I've been reading the code and it's a great example of how to create a multi tenant SaaS product.  I wanted to understand for my own purposes if this could be deployed in a self-hosted manner with more of a serverless / pay-per-use approach.  My thought was [API Gateway websockets](https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-websocket-api.html) + lambda.  I understand why it may not work for your hosted offering you run due to limits/quotas/latency, but assuming those are not a concern/blocker for self-hosting, are there any technical challenges to go with this approach?  Long-running process(es) (lambda limits - time, memory), preserving e2e encryption, some other security aspect, etc.?

If not, I'd look to build out and contribute back here.

Thanks in advance for any help!

**Comment by j-berman** [comment]
Thank you for your interest!

This would be challenging to implement because our design relies on the Userbase server to be stateful.

When a user signs in, their client establishes an authenticated WebSocket connection to the server. Every user-initiated write operation (or "transaction") is sent over this WebSocket. Once the transaction is successfully stored persistently in Dynamo DB, the Userbase server then pushes the transaction out to all connected clients that have that particular database open.

With this design in mind, the Userbase server is stateful for 2 main reasons:
1. To keep track of which clients are supposed to receive new transactions in real-time.
2. To ensure the server pushes transactions out to clients in the correct order.

[This](https://github.com/encrypted-dev/userbase/blob/249f1fc3eaad3d74fa4d1c20516d242403385b74/src/userbase-server/db.js#L576) would be a good place to start to see how the server uses state stored in memory to achieve both goals above.

I'm not familiar with the API Gateway, but my initial reaction is that safely replicating the server's statefulness would be the most challenging thing to achieve. I would guess you would need to push that state out to a database, and I'm not sure if the cost/benefit of doing so is worth it (keeping in mind the performance hit from latency + writing to/reading from disk).

**Comment by pfeilbr** [comment]
Thank you @j-berman for pointing out the stateful challenge and providing the detailed information.  I'll review the area of code pointed to.
