### ISSUE TITLE
SignUp Flow

### ISSUE THREAD

**Issue by ankitboghra** [encrypted-dev/userbase#2]
While signing up, after pressing the signup button, it did not move to the login page or logged me in.
Instead it kept showing the loader, i waited for 30 seconds.
But, the sign up was successful.
(Ubuntu, Chrome).

Also I did not get the key.

**Comment by dvassallo** [comment]
Thank you for reporting. I can't repro it at the moment, but will keep an eye on this.

BTW. You can get the key after signing in from the key icon on the top right.

**Comment by ankitboghra** [comment]
Cool, thanks.

**Comment by ankitboghra** [comment]
I am not able to get the key from the key icon too.
![Screenshot from 2019-07-18 14-58-13](https://user-images.githubusercontent.com/32591079/61446450-c77e0e00-a96c-11e9-8e89-ef3bc1c252ec.png)

**Comment by j-berman** [comment]
Following up on this, it's possible for an account to be created but for the key to not save properly in your browser.

We're currently discussing a larger overhaul to our sign up/sign in implementation that will prevent this issue, stay tuned! For now, it would be simplest to just create a new account.

Thank you again for creating this issue!

**More details on the issue**

This likely happened because of a random network error causing the sign up to timeout. Even though your username saved in our database, your browser didn't receive a response from the server saying it saved successfully and got stuck loading/waiting for a response.

Since we only generate and save the key after a successful response from the sign up endpoint on the server, your key was never generated for this account. So your account was created, but you don't have a key. The larger overhaul to our sign in/sign up implementation will fix this.

For now, we've added a 10 second timeout handler to all requests originated by the client that should time out. If signing up takes longer than 10 seconds for example, it'll show you an error so you can try again -- it won't just continue showing the loader. But the main issue still remains.

**Comment by j-berman** [comment]
This issue should be fixed! Closing, but feel free to re-open if it arises again.

Apologies for the late follow-up, a lot has changed since the above.

**Technical description of the new sign up approach**

(1) First, your browser generates a secret key (referred to in the code as a "seed"), then sends the server your provided username/password combo ([source](https://github.com/encrypted-dev/userbase/blob/1bc4112f3ea3030f1b5ecd6e572dff0eb4857339/src/client/encrypted-dev-sdk/auth.js#L12-L34)). If this username isn't taken, you receive a successful response from the server (but importantly, your account is not fully created yet).

(2) Next, your browser [saves your seed to local storage](https://github.com/encrypted-dev/userbase/blob/1bc4112f3ea3030f1b5ecd6e572dff0eb4857339/src/client/encrypted-dev-sdk/auth.js#L38).

(3) Finally, your browser establishes a web socket connection to the server. Your browser then proves ownership of the seed to the server. Once this is done, the server assumes your browser has safely saved the seed to local storage. Your account becomes "fully created" at this point, and no one else can take your username ([source](https://github.com/encrypted-dev/userbase/blob/1bc4112f3ea3030f1b5ecd6e572dff0eb4857339/src/server/auth.js#L162-L164)). Up until this point, anyone could have attempted to sign up with your username. So in the event there is a network error between steps 1 and 2 (which is what seemed to be the issue in your case), you could safely re-attempt to sign up.
